spring.application.name=file-storage
spring.datasource.url=jdbc:postgresql://localhost:5432/file_storage_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.sql.init.mode=embedded

minio.endpoint=http://localhost:9000
minio.access-key=${MINIO_USER}
minio.secret-key=${MINIO_PASSWORD}
minio.bucket=${MINIO_BUCKET}

spring.session.store-type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.session.redis.namespace=file-storage
server.servlet.session.timeout=30m

spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB


